/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>

#define VERBOSE 1
#if VERBOSE
#define LOG_V(...) {fprintf(stdout, __VA_ARGS__);fprintf(stdout, "\n");} 
#else
#define LOG_V(...)
#endif


#ifdef __cplusplus
extern "C" {
#endif


struct equation {
	char input[500];
};
typedef struct equation equation;

#define ARITHMETIC_PROG 0x23456789
#define ARITHMETIC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ARITHMETIC 1
extern  int * arithmetic_1(equation *, CLIENT *);
extern  int * arithmetic_1_svc(equation *, struct svc_req *);
extern int arithmetic_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ARITHMETIC 1
extern  int * arithmetic_1();
extern  int * arithmetic_1_svc();
extern int arithmetic_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_equation (XDR *, equation*);

#else /* K&R C */
extern bool_t xdr_equation ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
